

#define BAD_CDF_MERGE_EXCEPTION		515
#define BAD_CDF_COMPARE_EXCEPTION	516
#define BAD_CDF_ARGUMENT_OUT_OF_RANGE	517
#define ILLEGAL_CDF_STATE		518
#define ARGUMENT_INIT_ERROR             519
#define GENERATOR_INIT_ERROR		520
#define MATLAB_INIT_ERROR		521

