# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/default/Documents/Source/eclipse-cpp/Markov

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/default/Documents/Source/eclipse-cpp/Markov

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/default/Documents/Source/eclipse-cpp/Markov/CMakeFiles /home/default/Documents/Source/eclipse-cpp/Markov/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/default/Documents/Source/eclipse-cpp/Markov/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Test

# Build rule for target.
Test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test
.PHONY : Test

# fast build rule for target.
Test/fast:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/build
.PHONY : Test/fast

#=============================================================================
# Target rules for targets named ransample

# Build rule for target.
ransample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ransample
.PHONY : ransample

# fast build rule for target.
ransample/fast:
	$(MAKE) -f CMakeFiles/ransample.dir/build.make CMakeFiles/ransample.dir/build
.PHONY : ransample/fast

alias/ransampl.o: alias/ransampl.c.o
.PHONY : alias/ransampl.o

# target to build an object file
alias/ransampl.c.o:
	$(MAKE) -f CMakeFiles/ransample.dir/build.make CMakeFiles/ransample.dir/alias/ransampl.c.o
.PHONY : alias/ransampl.c.o

alias/ransampl.i: alias/ransampl.c.i
.PHONY : alias/ransampl.i

# target to preprocess a source file
alias/ransampl.c.i:
	$(MAKE) -f CMakeFiles/ransample.dir/build.make CMakeFiles/ransample.dir/alias/ransampl.c.i
.PHONY : alias/ransampl.c.i

alias/ransampl.s: alias/ransampl.c.s
.PHONY : alias/ransampl.s

# target to generate assembly for a file
alias/ransampl.c.s:
	$(MAKE) -f CMakeFiles/ransample.dir/build.make CMakeFiles/ransample.dir/alias/ransampl.c.s
.PHONY : alias/ransampl.c.s

args.o: args.cpp.o
.PHONY : args.o

# target to build an object file
args.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/args.cpp.o
.PHONY : args.cpp.o

args.i: args.cpp.i
.PHONY : args.i

# target to preprocess a source file
args.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/args.cpp.i
.PHONY : args.cpp.i

args.s: args.cpp.s
.PHONY : args.s

# target to generate assembly for a file
args.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/args.cpp.s
.PHONY : args.cpp.s

cdf.o: cdf.cpp.o
.PHONY : cdf.o

# target to build an object file
cdf.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/cdf.cpp.o
.PHONY : cdf.cpp.o

cdf.i: cdf.cpp.i
.PHONY : cdf.i

# target to preprocess a source file
cdf.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/cdf.cpp.i
.PHONY : cdf.cpp.i

cdf.s: cdf.cpp.s
.PHONY : cdf.s

# target to generate assembly for a file
cdf.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/cdf.cpp.s
.PHONY : cdf.cpp.s

markov.o: markov.cpp.o
.PHONY : markov.o

# target to build an object file
markov.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/markov.cpp.o
.PHONY : markov.cpp.o

markov.i: markov.cpp.i
.PHONY : markov.i

# target to preprocess a source file
markov.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/markov.cpp.i
.PHONY : markov.cpp.i

markov.s: markov.cpp.s
.PHONY : markov.s

# target to generate assembly for a file
markov.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/markov.cpp.s
.PHONY : markov.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ransample"
	@echo "... alias/ransampl.o"
	@echo "... alias/ransampl.i"
	@echo "... alias/ransampl.s"
	@echo "... args.o"
	@echo "... args.i"
	@echo "... args.s"
	@echo "... cdf.o"
	@echo "... cdf.i"
	@echo "... cdf.s"
	@echo "... markov.o"
	@echo "... markov.i"
	@echo "... markov.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

